#!/bin/sh

rm -r ./lib

mkdir -p lib/ios
cp build.ios/Debug-iphoneos/libXXX.a lib/ios/libXXX.a

mkdir -p lib/sim
cp build.sim/Debug-iphonesimulator/libXXX.a lib/sim/libXXX.a

mkdir -p lib/generic
lipo -create "lib/ios/libXXX.a" "lib/sim/libXXX.a" -output "lib/generic/libXXX.a"
